server:
  port: 8080

spring:
  application:
    name: bot-gateway

  cloud:
    nacos:
      discovery: # 必须是 discovery
        server-addr: 127.0.0.1:8848 # Nacos 的本地地址

# 提前预警：等你后面要打开 RocketMQ 时，注意端口号！
# 我们 Docker 里配置的 NameServer 端口是 9876，不是 9090
    stream:
      bindings:
        bot_gateway-out-1:
          destination: topic_msg_raw
          content-type: application/json
        bot_gateway-out-2:
          destination: topic_group_needs_raw
          content-type: application/json
        bot_gateway-out-3:
          destination: topic_user_needs_raw
          content-type: application/json

        rocketmq:
          binder:
            name-server: 127.0.0.1:9876
            vip-channel-enabled: false

napcat:
  url: http://127.0.0.1:3011
  token: "Bearer 1TTQ51pa-Q_Hr7kl"

jwt:
  secret: ${JWT_SECRET:c2VjcmV0S2V5Rm9ySld0VG9rZW5HZW5lcmF0aW9uSW5TcHJpbmdCb290QXBwbGljYXRpb24=}
