server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: bot_gateway

  cloud:
    nacos:
      discover:
        server-addr: 127.0.0.1:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9090