server:
  port: 8180

spring:
  application:
    name: sensitive_filter
  data:
    redis:
      host: ${MEMOECHO_REDIS_HOST:127.0.0.1}
      port: ${MEMOECHO_REDIS_PORT:6380}
      password: ${MEMOECHO_REDIS_PASSWORD:123456}
      database: ${MEMOECHO_REDIS_DB:0}
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    function:
      definition: botMsgConsumer;groupNeedsConsumer;privateNeedsConsumer
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          vip-channel-enabled: false
        bindings:
          botMsgConsumer-in-0:
            consumer:
              tags: group_msg_received
          groupNeedsConsumer-in-0:
            consumer:
              tags: group_msg_received
          privateNeedsConsumer-in-0:
            consumer:
              tags: private_msg_received
      bindings:
        botMsgConsumer-in-0:
          destination: topic_msg_raw
          group: sensitive-filter-group-read
        groupNeedsConsumer-in-0:
          destination: topic_group_needs_raw
          group: sensitive-filter-group-needs
        privateNeedsConsumer-in-0:
          destination: topic_user_needs_raw
          group: sensitive-filter-private-needs
        sensitive_filter-out-1:
          destination: topic_msg_clean
          content-type: application/json
        sensitive_filter-out-2:
          destination: topic_security_alerts
          content-type: application/json
        sensitive_filter-out-3:
          destination: topic_group_needs_clean
          content-type: application/json
        sensitive_filter-out-4:
          destination: topic_user_needs_clean
          content-type: application/json
