server:
  port: 8180

spring:
  application:
    name: sensitive_filter
  cloud:
    nacos:
      discovery: # 必须是 discovery
        server-addr: 127.0.0.1:8848 # Nacos 的本地地址

    # 提前预警：等你后面要打开 RocketMQ 时，注意端口号！
    # 我们 Docker 里配置的 NameServer 端口是 9876，不是 9090
    stream:
#        bot_gateway-out-1_1:
#          destination: topic_bot_messages
#          content-type: application/json
#        bot_gateway-out-2_1:
#          destination: topic_group_needs
#          content-type: application/json
#        bot_gateway-out-3_1:
#          destination: topic_user_needs
#          content-type: application/json
      function:
        definition: botMsgConsumer                 # 只有定义的组件才能分到MQ的流量
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          vip-channel-enabled: false
        bindings:
          botMsgConsumer-in-0:
            consumer:
              tags: group_msg_received
      bindings:
        botMsgConsumer-in-0:
          destination: topic_msg_raw
          group: sensitive-filter-group-read
        sensitive_filter-out-1:
          destination: topic_msg_clean
          content-type: application/json
        sensitive_filter-out-2:
          destination: topic_security_alerts
          content-type: application/json