server:
  port: 8380

spring:
  application:
    name: ai_brain
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos 的本地地址

    # 🚨 修正：function 必须和 stream 平级！
    function:
      definition: CleanMsgConsumer                 # 只有定义的组件才能分到MQ的流量

    # 提前预警：等你后面要打开 RocketMQ 时，注意端口号！
    # 我们 Docker 里配置的 NameServer 端口是 9876，不是 9090
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          vip-channel-enabled: false
        bindings:
          CleanMsgConsumer-in-0:
            consumer:
              tags: group_msg_filtered
      bindings:
        CleanMsgConsumer-in-0:
          destination: topic_msg_clean
          group: ai_brain_catchGroupMsg

memo-echo:
  ai:
    dashscope:
      api-key: sk-363167240c50469c823d9e2e72ba8da8
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1    # 模型地址
      model-name: text-embedding-v4                                  # 向量模型名字
      dimension: 384                                                 # 向量纬度
      chat-model-name: qwen-plus                                     # 对话模型名字
