server:
  port: 8380

spring:
  application:
    name: ai_brain
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    function:
      definition: CleanMsgConsumer;CleanGroupRequestConsumer;CleanPrivateRequestConsumer
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
          vip-channel-enabled: false
        bindings:
          CleanMsgConsumer-in-0:
            consumer:
              tags: group_msg_filtered
          CleanGroupRequestConsumer-in-0:
            consumer:
              tags: group_msg_filtered
          CleanPrivateRequestConsumer-in-0:
            consumer:
              tags: private_msg_filtered
      bindings:
        CleanMsgConsumer-in-0:
          destination: topic_msg_clean
          group: ai_brain_catchGroupMsg
        CleanGroupRequestConsumer-in-0:
          destination: topic_group_needs_clean
          group: ai_brain_catchGroupRequest
        CleanPrivateRequestConsumer-in-0:
          destination: topic_user_needs_clean
          group: ai_brain_catchPrivateRequest

memo-echo:
  ai:
    dashscope:
      api-key: sk-363167240c50469c823d9e2e72ba8da8
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      model-name: text-embedding-v4
      chat-modul-name: qwen-plus
      dimension: 512
    qdrant:
      host: 127.0.0.1
      port: 6334
      collection-name: schedule_embeddings
